platform:
  - x86
  #- x64

configuration:
  - Debug
  - Release

image: Visual Studio 2017

branches:
  except:
    - gh-pages

environment:
  CXXFLAGS: -DWIN32_LEAN_AND_MEAN

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cinst -y cmake.portable
  - ps: (new-object net.webclient).DownloadFile('https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.zip', 'C:\boost_1_66_0.zip')
  - ps: Add-Type -A System.IO.Compression.FileSystem
  - ps: "[IO.Compression.ZipFile]::ExtractToDirectory('C:\\boost_1_66_0.zip', 'C:\\')"
  - cd "C:\boost_1_66_0"
  - bootstrap.bat --with-toolset=msvc-15.0
  - b2 --with-container --with-context --with-coroutine --with-date_time --with-filesystem --with-system --with-regex --with=test
  - cd "%APPVEYOR_BUILD_FOLDER%"

build_script:
  - md "test\build"
  - cd "test\build"
  - set LDFLAGS="/SAFESEH:NO"
  - cmake -G"Visual Studio 15 2017" -DBOOST_ROOT="C:/boost_1_66_0" -DBoost_USE_STATIC_LIBS=ON ..
  - cmake --build .
  - ctest --output-on-failure -C Debug
