platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

os:
  - Visual Studio 2015 Update 1

branches:
  except:
    - gh-pages

install:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
  - cinst -y cmake
  - ps: (new-object net.webclient).DownloadFile('https://github.com/ned14/boost-release/archive/master.zip', 'C:\master.zip')
  - ps: Add-Type -A System.IO.Compression.FileSystem
  - ps: "[IO.Compression.ZipFile]::ExtractToDirectory('C:\\master.zip', 'C:\\')"
  - cd "C:\boost-release-master"
  - bootstrap.bat --with-toolset=msvc-14.0
  - b2 --with-container --with-context --with-coroutine --with-date_time --with-filesystem --with-system --with-test
  - cd "%APPVEYOR_BUILD_FOLDER%"

build_script:
  - md build
  - cd build
  - set LDFLAGS="/SAFESEH:NO"
  - cmake -DBUILD_SHARED_LIBS=YES -G"Visual Studio 14 2015" -DBOOST_ROOT="C:/boost-release-master" -DBoost_USE_STATIC_LIBS=ON -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=ON ..
  - cmake --build .
  - ctest --output-on-failure -C Debug
