/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef BOOST_HTTP_BASIC_ROUTER_H
#define BOOST_HTTP_BASIC_ROUTER_H

#include <vector>
#include <functional>

namespace boost {
namespace http {

template<class unary_predicate,
         class route_function_type,
         typename... arguments>
class basic_router: public std::vector<
                                std::pair<unary_predicate, route_function_type>
                            >
{
public:
    basic_router(std::initializer_list<std::pair<unary_predicate, route_function_type>> l):
        std::vector<std::pair<unary_predicate, route_function_type>>(l)
    {}

    basic_router(const basic_router&) = default;
    basic_router(basic_router&&) = default;

    bool operator()(const ::std::string& path, arguments... params)
    {
        for(auto& it : *this)
        {
            if (it.first(path))
            {
                it.second(params...);
                return true;
            }
        }
        return false;
    }
};

} // namespace http
} // namespace boost

#endif // BOOST_HTTP_BASIC_ROUTER_H
