[[basic_polymorphic_server_socket]]
==== `basic_polymorphic_server_socket`

[source,cpp]
----
#include <boost/http/polymorphic_server_socket.hpp>
----

This function inherits <<basic_polymorphic_socket_base,
`basic_polymorphic_socket_base<Message>`>> and extends its interface with
virtual functions useful for server sockets. This class itself is also a
abstract class with no state (i.e. an _interface_).

References for objects of this class are expected to fulfill the
<<server_socket_concept,`ServerSocket` concept>>.

This class is inherited by <<server_socket_adaptor,`server_socket_adaptor`>>.

===== Template parameters

`Message`::

  The message type.

===== Member types

These are the types chosen _set in stone_ to guarantee ABI stability across
binaries (including possible plugins).

`typedef std::string method_server_type`::

  The `server_type` suffix is used to avoid name clashing with a possible HTTP
  client abstraction.

`typedef std::string path_server_type`::

  The `server_type` suffix is used to avoid name clashing with a possible HTTP
  client abstraction.

`typedef boost::string_ref reason_phrase_server_type`::

  The `server_type` suffix is used to avoid name clashing with a possible HTTP
  client abstraction.

===== Member functions

====== Overwritable functions

These are the functions that subclasses need to implement in order to lose the
`abstract class` property.

`virtual bool write_response_native_stream() const = 0`::

  This function presents no differences (besides mandatory virtual) from the one
  with the same name found on the <<server_socket_concept, `ServerSocket`
  concept>>.

`virtual void async_read_request(method_server_type &method, path_server_type &path, message_type &message, callback_type handler) = 0`::

  The only difference between this function (besides mandatory virtual) and the
  one with the same name found on the <<server_socket_concept, `ServerSocket`
  concept>> is the lack of support for completion tokens and the use of a type
  erased handler instead.

`virtual void async_write_response(std::uint_fast16_t status_code, const reason_phrase_server_type &reason_phrase, const message_type &message, callback_type handler) = 0`::

  The only difference between this function (besides mandatory virtual) and the
  one with the same name found on the <<server_socket_concept, `ServerSocket`
  concept>> is the lack of support for completion tokens and the use of a type
  erased handler instead.

`virtual void async_write_response_continue(callback_type handler) = 0`::

  The only difference between this function (besides mandatory virtual) and the
  one with the same name found on the <<server_socket_concept, `ServerSocket`
  concept>> is the lack of support for completion tokens and the use of a type
  erased handler instead.

`virtual void async_write_response_metadata(std::uint_fast16_t status_code, const reason_phrase_server_type &reason_phrase, const message_type &message, callback_type handler) = 0`::

  The only difference between this function (besides mandatory virtual) and the
  one with the same name found on the <<server_socket_concept, `ServerSocket`
  concept>> is the lack of support for completion tokens and the use of a type
  erased handler instead.

`virtual ~basic_polymorphic_server_socket()`::

  Destructor.

====== Wrappers to fulfill the ASIO extensible model

These functions rewrite usual function calls in terms of the ABI stable
interface. They also enable the ASIO extensible model within this hierarchy.

`template<class CompletionToken> typename boost::asio::async_result<typename boost::asio::handler_type<CompletionToken, void(boost::system::error_code)>::type>::type async_read_request(method_server_type &method, path_server_type &path, message_type &message, CompletionToken &&token)`::

  Handle the token and dispatch the operation to the ABI stable
  `async_read_request`.

`template<class CompletionToken> typename boost::asio::async_result<typename boost::asio::handler_type<CompletionToken, void(boost::system::error_code)>::type>::type async_write_response(std::uint_fast16_t status_code, const reason_phrase_server_type &reason_phrase, const message_type &message, CompletionToken &&token)`::

  Handle the token and dispatch the operation to the ABI stable
  `async_write_response`.

`template<class CompletionToken> typename boost::asio::async_result<typename boost::asio::handler_type<CompletionToken, void(boost::system::error_code)>::type>::type async_write_response_continue(CompletionToken &&token)`::

  Handle the token and dispatch the operation to the ABI stable
  `async_write_response_continue`.

`template<class CompletionToken> typename boost::asio::async_result<typename boost::asio::handler_type<CompletionToken, void(boost::system::error_code)>::type>::type async_write_response_metadata(std::uint_fast16_t status_code, const reason_phrase_server_type &reason_phrase, const message_type &message, CompletionToken &&token)`::

  Handle the token and dispatch the operation to the ABI stable
  `async_write_response_metadata`.

===== See also

* <<polymorphic_server_socket,`polymorphic_server_socket`>>
