[[file_server_errc]]
==== `file_server_errc`

[source,cpp]
----
#include <boost/http/file_server.hpp>
----

[source,cpp]
----
enum class file_server_errc
----

This scoped enumeration defines the values for the error codes reported by HTTP
file server abstraction shipped with this library.

They're designed to work with <<file_server_errc_file_server_category,
file_server_category>>.

The traits `boost::system::is_error_code_enum` and
`boost::system::is_error_condition_enum` are specialized to recognize
`file_server_errc`.

===== Member constants

`io_error`::

  When any operation on the file stream fails or throws an exception.
+
NOTE: It's guaranteed that no operations on the underlying socket were done when
this error happens.

`irrecoverable_io_error`::

  When any operation on the file stream fails or throws an exception AFTER some
  operation on the underlying socket already was issued.

`write_state_not_supported`::

  If some write operation already was issued before the call to the function
  that raised this error code.

`file_not_found`::

  The requested file wasn't found. The channel is left untouched to give the
  user the opportunity to send a custom "404 response" or to further forward the
  request.

`file_type_not_supported`::

  The requested file was found but it is not regular (e.g. directories, block
  devices, links...). Channel remains untouched.

`filter_set`::

  The user provided filter predicate returned `false` to cancel the
  operation. Channel remains untouched.

===== Non-member functions

`boost::system::error_code make_error_code(file_server_errc e)`::

  Creates an error code using _e_ and <<file_server_errc_file_server_category,
  file_server_category>>

`boost::system::error_condition make_error_condition(file_server_errc e)`::

  Creates an error code using _e_ and <<file_server_errc_file_server_category,
  file_server_category>>

[[file_server_errc_file_server_category]]
===== file_server_category

[source,cpp]
----
const boost::system::error_category& file_server_category();
----

Obtains a reference to the static error category object for the file server
errors. The object overrides the member function `name` to return
`"file_server"` and overrides `message` to support all values from
`file_server_errc`.

===== See also

* <<async_response_transmit_file,`async_response_transmit_file`>>
* <<async_response_transmit_dir,`async_response_transmit_dir`>>
