[[filesystem_router]]
==== `filesystem_router`

[source,cpp]
----
#include <boost/http/filesystem_router.hpp>
----

Router that tests a path received by a connection, and tests if `root` + `path`
exists on disk.  If it exists, calls the `router` function with an arbitary
number of arguments.

For example, if the router is given these two routes:

    { "/tmp", send_picture }
    { "/home", read_news }

A client might request "http://server/news.html".  In this case, the filesystem_router
will first try to find a file "/tmp/news.html". If it fails to find such a file,
it will then proceed to the second route and try "/home/news.html".  If it then
succeeds, it will call the `read_news` function.

The `router` is an arbitary function, that must match the call to the router
itself.  So if we call the route as `basic_router(path, arg1, arg2)` the `router`
function will be called with `router(arg1, arg2)`.

===== Template parameters

`route_function_type`::
    Functor of the route destination function.

`typename... arguments`::
    List of argument type to be passed onto the route destination function.

===== See also

* <<basic_router, `basic_router`>>.
* <<regex_router, `regex_router`>>.
