[[message_concept]]
==== `Message`

A container able to hold generic HTTP messages.

===== Definitions

HTTP field name::

  A string encoded with the _ISO-8859-1_ charset whose contents are limited to
  the chars listed below (case-sensitive):
+
* A digit (i.e. `'0'`, `'1'`, `'2'`, `'3'`, `'4'`, `'5'`, `'6'`, `'7'`, `'8'` or
  `'9'`).
* A lowercase alphabetic (i.e. `'a'`, `'b'`, `'c'`, `'d'`, `'e'`, `'f'`, `'g'`,
  `'h'`, `'i'`, `'j'`, `'k'`, `'l'`, `'m'`, `'n'`, `'o'`, `'p'`, `'q'`, `'r'`,
  `'s'`, `'t'`, `'u'`, `'v'`, `'w'`, `'x'`, `'y'` or `'z'`).
* A few special characters: `'!'`, `'#'`, `'$'`, `'%'`, `'&'`, `'\''`, `'*'`,
  `'+'`, `'-'`, `'.'`, `'^'`, `'_'`, backtick (i.e. `'\x60'`), `'|'` or `'~'`.
+
NOTE: Any uppercase character received through the wire MUST be normalized
(i.e. converted to lowercase).

HTTP field value::

  A string encoded with the _ISO-8859-1_ charset whose contents are limited to
  the chars listed below (whether they're case-sensitive or not is defined on a
  header-by-header basis and, as such, they all are considered case-sensitive in
  this layer of abstraction):
+
* Any visible _USASCII_ character.
* Any character in the closed interval (i.e. both ends are inclusive) between
  `'\x80'` and `'\xFF'`. The use of these characters within the _HTTP field
  value_ is obsolete and should be avoided.
* Space (i.e. `'\x20'`) and horizontal tab (i.e. `'\t'`). These characters are
  not allowed in the beginning or in the end of the _HTTP field value_.

HTTP field::

  A pair whose first element is an _HTTP field name_ and second element is an
  _HTTP field value_.

HTTP header section::

  A set of _HTTP fields_ received in the same chunk (e.g. the HTTP header
  section defined in the RFC 7230).
+
NOTE: For fields with equivalent field names, the relative order is preserved.

===== Notation

`X`::

  A type that is a model of `Message`.

`Headers`::

  A type fulfilling the following requirements:

* The {cpp11} concept of associative containers (_associative.reqmts_)
  footnote:[The {cpp11} update gives extra guarantees about preserving the
  insertion ordering for elements with equivalent keys.].
* It supports equivalent keys.
* Value type is equal to `pair<const Key, T>`.
* `mapped_type` is available with the same semantics for multimap.
* `Headers::key_type` MUST fulfill the requirements for the `String` concept
  (i.e. `std::basic_string`).
+
`Headers::key_type::value_type` MUST be able to represent all values in the
_ISO-8859-1_ charset except for the upper case versions of the alphabetic
characters.
+
WARNING: Inserting elements in `Headers` instances whose keys contains uppercase
char(s) invoke undefined behaviour.
* `Headers::mapped_type` MUST fulfill the requirements for the `String` concept
  (i.e. `std::basic_string`).
+
`Headers::mapped_type::value_type` MUST be able to represent all values in the
_ISO-8859-1_ charset.

`Body`::

  A type fulfilling the C++ concept of sequence containers (_sequence.reqmts_)
  whose `value_type` can represent byte octets.

`a`::

  Object of type `X`.

`ca`::

  Object of type `const X`.

===== Requirements

[options="header"]
|===
|Expression|Return type|Precondition|Semantics|Postcondition

|`std::is_base_of<std::true_type, boost::http::is_message<X>>`|`std::true_type`| | |

|`X::headers_type`|`Headers`| | |

|`X::body_type`|`Body`| | |

|`a.headers()`|`X::headers_type&`|
a|
* It should be used to represent the _HTTP header section_ received/to-be-sent
  before the HTTP body data payload.
* Always returns a reference to the same object.
* The returned object MUST *NOT* be shared with the one returned by
  `a.trailers()`.
|

|`ca.headers()`|`const X::headers_type&`|
a|
* It should be used to represent the _HTTP header section_ received/to-be-sent
  before the HTTP body data payload.
* Always returns a reference to the same object.
* The returned object MUST *NOT* be shared with the one returned by
  `a.trailers()`.
|

|`a.body()`|`X::body_type&`|
a|
* It should be used to represent chunks of the HTTP body data payload.
* Always returns a reference to the same object.
|

|`ca.body()`|`const X::body_type&`|
a|
* It should be used to represent chunks of the HTTP body data payload.
* Always returns a reference to the same object.
|

|`a.trailers()`|`X::headers_type&`|
a|
* It should be used to represent the _HTTP header section_ received/to-be-sent
  after the HTTP body data payload.
* Always returns a reference to the same object.
* The returned object MUST *NOT* be shared with the one returned by
  `a.headers()`.
|

|`ca.trailers()`|`const X::headers_type&`|
a|
* It should be used to represent the _HTTP header section_ received/to-be-sent
  after the HTTP body data payload.
* Always returns a reference to the same object.
* The returned object MUST *NOT* be shared with the one returned by
  `a.headers()`.
|
|===

. Failing to comply with the "MUST" and "MUST *NOT*" conditions described
  previously invokes undefined behaviour.

===== Models

* <<message,`message`>>
* <<basic_message,`basic_message`>>
