[[read_state]]
==== `read_state`

[source,cpp]
----
#include <boost/http/read_state.hpp>
----

[source,cpp]
----
enum class read_state
----

Represents the current state in the HTTP incoming request or HTTP incoming
response.

Be prepared to face multiple state changes after a single action is scheduled
(e.g. you issue `read_message` action and the state already changed to
`finished` when the handler is invoked).

===== Member constants (incoming request)

[plantuml,read_request_state,title="Incoming request"]
----
@startuml
state empty
state message_ready
state body_ready
state finished

[*] --> empty
finished --> [*]

empty --> message_ready : read_request
empty --> body_ready : read_request
empty --> finished : read_request

message_ready --> message_ready : read_some
message_ready --> body_ready : read_some
message_ready --> finished : read_some

body_ready --> finished : read_some
@enduml
----

`empty`::

  This is the initial state. It means that the request object wasn't read yet.
+
At this state, you can only issue a `read_request` action.

`message_ready`::

  This state is reached from the `empty` state, once you ask for a new message.
+
No more `read_request` actions can be issued from this state.
+
From this state, you can issue the `read_some` action. The state will change to
`body_ready` once all body was read. In streaming connections (e.g. HTTP/1.1
chunked entities), this condition (body fully received) might never happen.
+
Once this state is reached, you can safely use the read start line and the
headers.

`body_ready`::

  This state is reached from the `message_ready`, once the http producer
  (e.g. embedded server) fully received the message body.
+
From this state, you can only issue the `read_some` action.
+
Once this state is reached, you can safely assume that no more body parts will
be received.

`finished`::

  It means the message is complete and you can no longer issue another
  `read_request` until something else is done (e.g. send another http
  response). This is a different/special value, because the “something else to
  do” might not be related to read actions.
+
It can be reached from `body_ready` state, after all trailers have been
received. It's safe to assume that all message data is available at the time
this state is reached.

===== Member constants (incoming response)

[plantuml,read_response_state,title="Incoming response"]
----
@startuml
state empty
state message_ready
state body_ready
state finished

note right of finished : unused

[*] --> empty

empty --> message_ready : read_response
empty --> body_ready : read_response
empty --> empty : read_response

message_ready --> message_ready : read_some
message_ready --> body_ready : read_some
message_ready --> empty : read_some

body_ready --> empty : read_some
@enduml
----

`empty`::

  This is the initial state.
+
There are two ways to interpret this state. It might mean that the response
object wasn't read yet.
+
Another interpretation is that it was reached from the `body_ready` state
(directly — through a call to `read_some` — or indirectly — through a call to
`read_response`), after all trailers have been received. It's safe to assume
that all message data is available if this is the case.
+
At this state, you can only issue a `read_response` action.

`message_ready`::

  This state is reached from the `empty` state, once you ask for a new message.
+
No more `read_response` actions can be issued from this state.
+
From this state, you can issue the `read_some` action. The state will change to
`body_ready` once all body was read. In streaming connections (e.g. HTTP/1.1
chunked entities), this condition (body fully received) might never happen.
+
Once this state is reached, you can safely use the read start line and the
headers.

`body_ready`::

  This state is reached from the `message_ready`, once the http producer
  (e.g. an http client) fully received the message body.
+
From this state, you can only issue the `read_some` action.
+
Once this state is reached, you can safely assume that no more body parts will
be received.

`finished` (*UNUSED*)::
+
NOTE: Only makes sense in server mode, when reading an incoming request. In
client mode, `empty` target state is used instead.

===== See also

* <<write_state,`write_state`>>
* <<socket_concept,`Socket`>>
