[[request_continue_required]]
==== `request_continue_required`

[source,cpp]
----
#include <boost/http/algorithm/query.hpp>
----

[source,cpp]
----
template<class Request>
bool request_continue_required(const Request &request)
----

Check if the request represented by _request_ requires a “100 (Continue)
response” footnote:[Defined in RFC 7231, section 5.1.1.].

If you can properly process and reply the message without its body, you're free
to go. Otherwise, you should send a “100 (Continue) response” to ask for the
message body from the HTTP client.

This feature was designed to decrease network traffic, by allowing servers to
sooner reject messages that would be discarded anyway.

The name _required_ is used instead _supported_, because an action from the
server is required.

===== Template parameters

`Request`::

  A type fulfilling the requirements for the <<request_concept, `Request`
  concept>>.

===== Parameters

`const Request &request`::

  The read message.

===== Return value

Whether the request represented by _request_ requires a “100 (Continue)
response”.
