[[server_socket_concept]]
==== `ServerSocket`

Provides operations for HTTP servers.

===== Refinement of

* <<socket_concept,`Socket`>>

===== Definitions

Types fulfilling the `ServerSocket` concept and also possessing the _strict_ property::

  Instances from this type will *not* insert illegal characters
  footnote:[Defined in the <<message_concept,`Message` concept's "definitions"
  section>>.] in the HTTP fields.

===== Notation

`Message`::

  A type fulfilling the requirements for the <<message_concept,`Message`
  concept>>.

`m`::

  Object of type `Message`.

`cm`::

  Object of type `const Message`.

`CompletionToken`::

  A type fulfilling the concept of a completion token, as defined in
  https://isocpp.org/files/papers/n4045.pdf[N4045: Library Foundations for
  Asynchronous Operations, Revision 2].

`AsyncResultType`::

+
[source,cpp]
----
boost::asio::async_result<
     boost::asio::handler_type<
         CompletionToken, void(boost::system::error_code)>::type>::type
----

`token`::

  An object of the type `CompletionToken`.

`X`::

  A type that is a model of `ServerSocket`.

`a`::

  Object of type `X`.

`ca`::

  Object of type `const X`.

`sc`::

  A value of type `std::uint_fast16_t`.

===== Requirements

[options="header"]
|===
|Expression|Return type|Precondition|Semantics|Postcondition

|`std::is_base_of<std::true_type, boost::http::is_server_socket<X>>`
|`std::true_type`| | |

|`X::method_server_type`|
|`ServerSocket` only supports operations involving a single type of method.
|Must be a type fulfilling the requirements for the `String` concept (i.e.
 `std::basic_string`).
|

|`X::path_server_type`|
|`ServerSocket` only supports operations involving a single type of path.
|Must be a type fulfilling the requirements for the `String` concept (i.e.
 `std::basic_string`).
|

|`X::reason_phrase_server_type`|
|`ServerSocket` only supports operations involving a single type of reason
 phrase.
|Must be a type fulfilling the requirements for the `StringRef` concept (i.e.
 `boost::basic_string_ref`).
|

|`ca.write_response_native_stream()`|`bool`
|`a.read_state() != read_state::empty`
|Returns whether the current message exchange supports native stream.
|The same value and property is maintained until the end of the current message
 exchange.

|`method`||
|Object of method type supported by `X` (i.e. `X::method_server_type` if only
 one method type is supported or any type fulfilling the requirements of the
 `String` concept (i.e. `std::basic_string`) otherwise).
|

|`path`||
|Object of path type supported by `X` (i.e. `X::path_server_type` if only one
 path type is supported or any type fulfilling the requirements of the `String`
 concept (i.e. `std::basic_string`) otherwise).
|

|`reason_phrase`||
|Const object of reason phrase type supported by `X`
 (i.e. `X::reason_phrase_server_type` if only one reason phrase type is
 supported or any type fulfilling the requirements of the `StringRef` concept
 (i.e. `boost::basic_string_ref`) otherwise).
|

|`a.async_read_request(method, path, m, token)`|`AsyncResultType`
|`a.read_state() == read_state::empty`
|Initiate an asynchronous operation to read enough of the message to apply the
 request to a target resource (i.e. request line plus the header section).
 Handler is called when the operation completes with an appropriate parameter.

 `method`, `path` and `m` are left in a unspecified state while the operation is
 in progress.

 The ServerSocket object MUST prevent the user from issuing new replies while
 the request isn't ready. The prevention MUST be done by changing the write
 state to `write_state::finished` while the read_request operation is in
 progress.
|By the time the handler is called, `method` value represents the read method,
 `path` represents the read url and all headers for the current request are
 inserted into `m.headers()`, if no error happened.

|`a.async_read_request(method, path, m, token)`|`AsyncResultType`
|`a.read_state() != read_state::empty`
|No actions are done and the handler from the completion token is called with
 `boost::system::error_code {http_errc::out_of_order}`.
|

|`a.async_write_response(sc, reason_phrase, cm, token)`|`AsyncResultType`
|`a.write_state() == write_state::empty
  \|\| a.write_state() == write_state::continue_issued`
|Initiate an asynchronous operation to write the response message (atomic
 message). Handler is called when the operation completes with an appropriate
 parameter.

 `reason_phrase` and `cm` MUST *NOT* be modified while the operation is in
 progress.
a|

* `a.write_state() == write_state ::finished`
* By the time the handler is called, the `cm` message is considered delivered,
  if no error happened.

|`a.async_write_response(sc, reason_phrase, cm, token)`|`AsyncResultType`
|`a.write_state() != write_state::empty
 && a.write_state() != write_state::continue_issued`
|No actions are done and the handler from the completion token is called with
 `boost::system::error_code {http_errc::out_of_order}`.
|

|`a.async_write_response_continue (token)`|`AsyncResultType`
|`a.write_state() == write_state::empty`
|Initiate an asynchronous operation to write a response with the semantics from
 a "100 (Continue) response" footnote:[Defined in RFC 7231, section
 5.1.1.]. Handler is called when the operation completes with an appropriate
 parameter.
a|

* `a.write_state() == write_state ::continue_issued`
* By the time the handler is called, the "100 (Continue) response" is
  considered delivered.

|`a.async_write_response_continue (token)`|`AsyncResultType`
|`a.write_state() != write_state::empty`
|No actions are done and the handler from the completion token is called with
 `boost::system::error_code {http_errc::out_of_order}`.
|

|`a .async_write_response_metadata(sc, reason_phrase, cm, token)`
|`AsyncResultType`
|`(a.write_state() == write_state::empty
   \|\| a.write_state() == write_state::continue_issued)
  && a.write_response_native_stream() == true`
|Initiate an asynchronous operation to write the response metadata (chunked
 message). Handler is called when the operation completes with an appropriate
 parameter.

 `reason_phrase` and `cm.headers()` MUST *NOT* be modified while the operation
 is in progress.
a|

* `a.write_state() == write_state ::metadata_issued`
* By the time the handler is called, the response metadata (i.e. `sc`,
  `reason_phrase` and `cm.headers()`) is considered delivered, if no error
  happened.

|`a .async_write_response_metadata(sc, reason_phrase, cm, token)`
|`AsyncResultType`
|`a.write_state() != write_state::empty
  && a.write_state() != write_state::continue_issued`
|No actions are done and the handler from the completion token is called with
 `boost::system::error_code {http_errc::out_of_order}` footnote:[The
 notification of the error `http_errc::out_of_order` has priority over
 `http_errc::native_stream_unsupported` because these errors present a
 programming logic error that always will happen (i.e. they aren't tied to
 specific runtime behaviour). If they aren't fixed, the program won't work
 either way.].
|

|`a .async_write_response_metadata(sc, reason_phrase, cm, token)`
|`AsyncResultType`
|`(a.write_state() == write_state::empty
   \|\| a.write_state() == write_state::continue_issued)
  && a.write_response_native_stream() == false`
|No actions are done and the handler from the completion token is called with
 `boost::system::error_code {http_errc ::native_stream_unsupported}`.
|

|===

. Failing to comply with the "MUST" and "MUST *NOT*" conditions described
  previously invokes undefined behaviour.
. Any HTTP field name received through the wire is normalized (i.e. uppercase
  characters are converted to lowercase) before they're inserted into objects of
  type `Message::headers_type`.
. If the user pass a `"connection: close"` header on the message object passed
  as argument to the `async_write_response` or `async_write_response_metadata`
  member-functions and no errors arose during the delivery of the message, the
  `ServerSocket` MUST call the handler with <<http_errc,
  `http_errc::stream_finished`>>.
+
This behaviour is intended for the communication between the user of this
library and the `ServerSocket` and can differ from the communication between the
`ServerSocket` and the underlying channel.
. If the `ServerSocket` reads a message that expects a "100 (Continue)
  response", it MUST insert the `"expect: 100-continue"` header and only one
  element with the HTTP field name `"expect"` MUST be present.
+
This behaviour is intended for the communication between the user of this
library and the `ServerSocket` and can differ from the communication between the
`ServerSocket` and the underlying channel.
. If the `ServerSocket` reads a message that does *NOT* expect a "100 (Continue)
  response", it MUST erase all the `"expect: 100-continue"` headers.
+
This behaviour is intended for the communication between the user of this
library and the `ServerSocket` and can differ from the communication between the
`ServerSocket` and the underlying channel.
. If the `ServerSocket` reads a message that represent a desire from the HTTP
  client to initiate a protocol upgrade, the `ServerSocket` supports a protocol
  upgrade and it'll communicate the client desire to the user of this library,
  it MUST communicate the desire ensuring all of the following conditions:
+
--
* Ensuring that the `"upgrade"` (case-insensitive) string is present in the
  comma-separated list of values from some `"connection"` header. This rule
  implictly requires the presence of at least one `"connection"` header.
* There is at least one `"upgrade"` header and all of the `"upgrade"` headers
  respect the conditions established in the section 6.7 of the RFC7230.
--
+
This behaviour is intended for the communication between the user of this
library and the `ServerSocket` and can differ from the communication between the
`ServerSocket` and the underlying channel.
. If the `ServerSocket` isn't willing to provide a protocol upgrade, then no
  `"upgrade"` headers can be present (in other words, all `"upgrade"` headers
  MUST be erased before delivering the message to the user of this library).
+
This behaviour is intended for the communication between the user of this
library and the `ServerSocket` and can differ from the communication between the
`ServerSocket` and the underlying channel.
. If the `"content-length"` header is provided to `async_write_response`, then
  the `ServerSocket` MUST ignore the message body (i.e. there is no data payload
  in the reply message) and SHOULD use the user-provided header.
+
The `ServerSocket` MUST adopt a behaviour that is compatible with the behaviour
defined in the section 3.3.2 of the RFC 7230.
. The `Socket` object MUST *NOT* insert HTTP headers with empty keys (i.e. `""`)
  or empty values (i.e. `""`) in message objects provided by the user.

===== Models

* <<basic_socket,`basic_socket`>>
* <<basic_buffered_socket,`basic_buffered_socket`>>
* <<polymorphic_server_socket,`polymorphic_server_socket`>>
* <<server_socket_adaptor,`server_socket_adaptor`>>
