[[socket_concept]]
==== `Socket`

Common operations between request and response that the underlying channel
should provide.

===== Definitions

Types fulfilling the `Socket` concept and also possessing the _strict_ property::

  Instances from this type will *not* insert illegal characters
  footnote:[Defined in the <<message_concept,`Message` concept's "definitions"
  section>>.] in the HTTP fields.

Native stream::

  The message size doesn't need to be know prior to writing the response
  message. The use of the streaming API can only be used when this property
  holds. Buffering the body MUST *NOT* be done and the message parts MUST be
  written as soon as convenient. If this property holds, the user MAY safely use
  the socket to transmit a live video stream, for instance.

Message metadata::

  The HTTP status line plus the header section.

Atomic message::

  A message which is issued and fully know with a single API call.
+
Every message is either atomic or chunked.

Chunked message::

  A message which is issued among several API calls.
+
Every message is either atomic or chunked.
+
Chunked messages are useful if you don't know the message in advance (e.g. video
streaming). These messages can only be used if native stream is supported.
+
You always need to be prepared to receive chunked messages and it's only useful
to differ operations which only apply to atomic messages or chunked messages
when you're about to send a message.

===== Notation

`Message`::

  A type fulfilling the requirements for the <<message_concept,`Message`
  concept>>.

`m`::

  Object of type `Message`.

`cm`::

  Object of type `const Message`.

`CompletionToken`::

  A type fulfilling the concept of a completion token, as defined in
  https://isocpp.org/files/papers/n4045.pdf[N4045: Library Foundations for
  Asynchronous Operations, Revision 2].

`AsyncResultType`::

+
[source,cpp]
----
boost::asio::async_result<
    boost::asio::handler_type<
        CompletionToken, void(boost::system::error_code)>::type>::type
----

`token`::

  An object of the type `CompletionToken`.

`X`::

  A type that is a model of `Socket`.

`a`::

  Object of type `X`.

`ca`::

  Object of type `const X`.

===== Requirements

[options="header"]
|===
|Expression|Return type|Precondition|Semantics|Postcondition

|`std::is_base_of<std::true_type, boost::http::is_socket<X>>`
|`std::true_type`| | |

|`a.get_io_service()`|`asio::io_service&`|
|Returns the `io_service` object through which the handlers of asynchronous
 operations will be invoked.
|

|`X::message_type`|
|`Socket` only supports operations involving a single type of message.
|Must be a type fulfilling the <<message_concept,`Message` concept>>.
|

|`ca.is_open()`|`bool`||Determine whether the socket is open.|

|`ca.read_state()`|<<read_state,`read_state`>>|
|Returns the state associated with the `Socket` meaningful for reading
 operations.
|

|`ca.write_state()`|<<write_state,`write_state`>>|
|Returns the state associated with the `Socket` meaningful for writing
 operations.
|

|`a.async_read_some(m, token)`|`AsyncResultType`
|`a.read_state() == read_state::message_ready`
|Initiate an asynchronous operation to read a part of the message body. Handler
 is called when at least one byte is read (called with no error set), when the
 end of message is reached (called with no error set) or when some error occurs.

 `m.body()` and `m.trailers()` are left in an unspecified state while the
 operation is in progress.
|By the time the handler is called, the part of the message read (if any) is
 appended to `m.body()`, if no error happened.

|`a.async_read_some(m, token)`|`AsyncResultType`
|`a.read_state() != read_state::message_ready`
|No actions are done and the handler from the completion token is called with
 `boost::system::error_code {http_errc::out_of_order}`.
|

|`a.async_read_trailers(m, token)`|`AsyncResultType`
|`a.read_state() == read_state::body_ready`
|Initiate an asynchronous operation to read the trailers. Handler is called when
 the rest of the message is fully received (called with no error set) or when
 some error occurs.

 `m.trailers()` is left in an unspecified state while the operation is in
 progress.
a|By the time the handler is called, if no error happened:

* `a.read_state() == http::read_state::empty`
* The read trailers (if any) are inserted into `m.trailers()`.

|`a.async_read_trailers(m, token)`|`AsyncResultType`
|`a.read_state() != read_state::body_ready`
|No actions are done and the handler from the completion token is called with
 `boost::system::error_code {http_errc::out_of_order}`.
|

|`a.async_write(cm, token)`|`AsyncResultType`
|`a.write_state() == write_state ::metadata_issued`
|Initiate an asynchronous operation to write a chunk of the HTTP body data
 payload (chunked message). Handler is called when the operation completes with
 an appropriate parameter.

 `cm.body()` MUST *NOT* be modified while the operation is in progress.
|By the time the handler is called, the `cm.body()` data is considered
 delivered, if no error happened.

|`a.async_write(cm, token)`|`AsyncResultType`
|`a.write_state() != write_state ::metadata_issued`
|No actions are done and the handler from the completion token is called with
 `boost::system::error_code {http_errc::out_of_order}`.
|

|`a.async_write_trailers(cm, token)`|`AsyncResultType`
|`a.write_state() == write_state ::metadata_issued`
|Initiate an asynchronous operation to write the trailer part of the message
 (chunked message). Handler is called when the operation completes with an
 appropriate parameter.

 `cm.trailers()` MUST *NOT* be modified while the operation is in progress.
a|

* `a.write_state() == write_state::finished`
* By the time the operation completes, the `cm.trailers()` data is considered
  delivered, if no error happened.

|`a.async_write_trailers(cm, token)`|`AsyncResultType`
|`a.write_state() != write_state ::metadata_issued`
|No actions are done and the handler from the completion token is called with
 `boost::system::error_code {http_errc::out_of_order}`.
|

|`a.async_write_end_of_message (token)`|`AsyncResultType`
|`a.write_state() == write_state ::metadata_issued`
|Initiate an asynchronous operation to signalize the sent message is complete
 (chunked message). Handler is called when the operation completes with an
 appropriate parameter.
a|

* `a.write_state() == write_state::finished`
* By the time the operation completes, the message is considered complete, if no
  error happened.

|`a.async_write_end_of_message (token)`|`AsyncResultType`
|`a.write_state() != write_state ::metadata_issued`
|No actions are done and the handler from the completion token is called with
 `boost::system::error_code {http_errc::out_of_order}`.
|

|===

. Failing to comply with the "MUST" and "MUST *NOT*" conditions described
  previously invokes undefined behaviour.
. Any HTTP field name received through the wire is normalized (i.e. uppercase
  characters are converted to lowercase) before they're inserted into objects of
  type `Message::headers_type`.
. The `Socket` object has the freedom to store information required to further
  process the incoming message in the user-provided `message` object. Thus, the
  library user MUST *NOT* use different `message` objects in the functions that
  initiate *read* operations, in the context of the *same* message exchange
  (i.e. the user can use a different `message` object to receive a different
  message). This requirement is extended to refinements of this concept.
. The `Socket` object MUST *NOT* insert HTTP headers with empty keys (i.e. `""`)
  or empty values (i.e. `""`) in message objects provided by the user.
. You MUST *NOT* write messages with the `"transfer-encoding: chunked"` header.
. You MUST *NOT* write *atomic* messages with the `"transfer-encoding"` header.

===== Models

* <<basic_socket,`basic_socket`>>
* <<basic_buffered_socket,`basic_buffered_socket`>>
* <<polymorphic_socket_base,`polymorphic_socket_base`>>
* <<polymorphic_server_socket,`polymorphic_server_socket`>>
* <<server_socket_adaptor,`server_socket_adaptor`>>

===== See also

* <<server_socket_concept,`ServerSocket`>>
