[[write_state]]
==== `write_state`

[source,cpp]
----
#include <boost/http/write_state.hpp>
----

[source,cpp]
----
enum class write_state
----

[plantuml,write_response_state,title="Outgoing response"]
----
@startuml
state " " as empty {
  state "empty" as iempty
  state continue_issued

  [*] --> iempty

  iempty --> continue_issued : write_response_continue
}
state metadata_issued
state finished

[*] --> empty
finished --> [*]

empty --> finished : write_response
empty --> metadata_issued : write_response_metadata

metadata_issued --> metadata_issued : write
metadata_issued --> finished : write_trailers,write_end_of_message
@enduml
----

[plantuml,write_request_state,title="Outgoing request"]
----
@startuml
state empty
state continue_issued
state metadata_issued
state finished

note right of continue_issued : unused
note right of finished : unused

[*] --> empty

empty --> empty : write_request
empty --> metadata_issued : write_request_metadata

metadata_issued --> metadata_issued : write
metadata_issued --> empty : write_trailers,write_end_of_message
@enduml
----

Represents the current state in the HTTP outgoing response or HTTP outgoing
request.

It has extra values that won't be used in “outgoing-request” mode.

===== Member constants

`empty`::

  This is the initial state.
+
It means that the request/response object wasn't used yet.
+
At this state, you can only issue the metadata or issue a continue action, if
continue is supported/used in this HTTP session. Even if continue was requested,
issue a continue action is optional and only required if you need the request's
body.

`continue_issued`::

  This state is reached from the `empty` state, once you issue a continue
  action.
+
No more continue actions can be issued from this state.
+
NOTE: Only makes sense in server mode, when issuing an outgoing response.

`metadata_issued`::

  This state can be reached either from `empty` or `continue_issued`.
+
It happens when the metadata (start line + header section) is reached (through
`write_metadata`).
+
From this state, you can only issue the body, the trailers or the end of the
message.

`finished`::

  The message is considered complete once this state is reached.
+
You can no longer issue anything once this state is reached. The underlying
channel will change the outgoing_state once some unspecified event occurs. This
event is usually a new request in server mode or the response fully received in
client mode.

===== See also

* <<read_state,`read_state`>>
* <<socket_concept,`Socket`>>
