== Using

=== Requirements

This library is written in {cpp11} and requires a {cpp11} supporting compiler.

This library tries to reuse standard library components when possible, but this
is not always the case. `std::error_code`, for instance, cannot be transparently
replaced by `boost::system::error_code` within ASIO-using code.

The full list of dependencies is:

* CMake 3.1.0 or newer footnote:[for tests]. You can skip this requirement if
  you don't intend to run the tests.
* Boost 1.70 or newer.
** algorithm, container, string_view, ASIO, date_time and system footnote:[Used
   in the core library.].
** unit_test_framework footnote:[For tests.].
** context and coroutine footnote:[For the examples and tests.].
** filesystem footnote:[For the `file_server`.].
* http://asciidoctor.org/[asciidoctor],
  https://github.com/asciidoctor/asciidoctor-diagram/[asciidoctor-diagram],
  http://plantuml.com/[PlantUML] and https://kevinpt.github.io/syntrax/[syntrax]
  footnote:[For the documentation.]. You'll also need http://pandoc.org/[pandoc]
  if you want to generate the ePUB output.
