#ifndef BOOST_HTTP_DETAIL_MACROS
#define BOOST_HTTP_DETAIL_MACROS

#ifndef BOOST_HTTP_DETAIL_UNREACHABLE
#ifdef NDEBUG
#define BOOST_HTTP_DETAIL_UNREACHABLE(m) ((void)0)
#else
#define BOOST_HTTP_DETAIL_STRINGIFY_AUX(x) #x
#define BOOST_HTTP_DETAIL_STRINGIFY(x) BOOST_HTTP_DETAIL_STRINGIFY_AUX(x)
#define BOOST_HTTP_DETAIL_LINE_STR BOOST_HTTP_DETAIL_STRINGIFY(__LINE__)
#define BOOST_HTTP_DETAIL_UNREACHABLE(m) (throw __FILE__ ":" BOOST_HTTP_DETAIL_LINE_STR ": UNREACHABLE: " m)
#endif // NDEBUG
#endif // BOOST_HTTP_DETAIL_UNREACHABLE

#endif // BOOST_HTTP_DETAIL_MACROS
